### ISSUE TITLE
? characters in process captured output

### ISSUE THREAD

**Issue by mhrimaz** [se2p/programming-styles-ss-2020-public-tests#18]
The output of my program is correct. However, I am failing all the test cases. I tried to run the test cases in IntelliJ.
this is an example output of my program:
![1111](https://user-images.githubusercontent.com/17963017/81496868-161be080-92d0-11ea-96f6-20401e38a27a.PNG)
Here is the difference between the captured output from ProcessBuilder and the expected output. As you can see all those extended ascii characters printed as `?`.
![difff](https://user-images.githubusercontent.com/17963017/81496900-41063480-92d0-11ea-8d90-39e07d5ce44a.PNG)
Test cases fails both on Windows and Linux machine.
What is the source of the problem?

**Comment by stocker4141** [comment]
This has to be an encoding issue.
What encoding is used for the expected / actual output ?

Maybe you can try to add a `-Dfile.encoding=UTF-8` flag to the call to the tests:
Like:
`java "-Dfile.encoding=UTF-8"  <...> BasicTest` 
The " is required on windows since it misinterprets the . otherwise.

I can see if I can add some code that forces UTF-8 encoding to the makefile and the PSTestUtils.java and push it to my fork, if that helps you @mhrimaz ?

**Comment by mhrimaz** [comment]
I added `-Dfile.encoding=UTF-8` but it still don't work. I also added this `(new InputStreamReader(process.getInputStream(), "UTF-8"));` but no difference.



I am directly using the character inside my code. The output in IDE and console is correct.
Do you think this is the source of the problem?

` = '▓';`

**Comment by stocker4141** [comment]
Do you pass the Encoding also as an argument in `executePreysAndHuntersWithArgs`?
Something like the following snippet might help:
```
public final static String ENCODING = "\"-Dfile.encoding=UTF-8\"";
public static Map<String, Object> executePreysAndHuntersWithArgs(String... args) throws Exception {
        List<String> _args = new ArrayList<String>();
        _args.add(getJava());
        // In order to correctly invoke PreyAndHunters we need to set its class path
        _args.add(ENCODING);
        _args.add("-cp");
        _args.add(getPreysAndHunter());
        _args.add(PREYS_AND_HUNTERS_CLASS_NAME);
        for (String arg : args) {
            _args.add(arg);
        }
...
```

As far as i can tell I use the same character for my shades (U+2593).
If that does not work than it is not related to encoding.
Since the output of the preysAndHunters program is set to be UTF-8, the reader is set to be UTF-8 and the output of the test program is set to be UTF-8, the outputs should match.
The only reason for a different encoding then would be console settings, but that should only affect the outputs after the comparison was made.

**Comment by mhrimaz** [comment]
`_args.add(getJava());` with this now the outputs are correct. 

Thanks for your help

**Comment by alessiogambi** [comment]
So can we close this issues?

**Comment by mhrimaz** [comment]
I am not sure this issue will happen in testing infrastructure or not.

**Comment by alessiogambi** [comment]
Uhm... where was the problem? in the test code or in your code? `getJava()` is quite an important parameter...

**Comment by stocker4141** [comment]
Best theory i have on whats happening is, that somewhere the output is interpreted with the wrong encoding and it breaks, resulting in the "?" being shown.
Most likely it could be that the tested program outputs in cp850 (default for windows powershell) and the test program reads it input in cp1252 (default for java under windows).
Under Linux there should be no issue since the default encoding is UTF-8 if I am not mistaken.

The snippet I posted above sets the file encoding for the tested program to UTF-8. 
This information must be passed to the InputStreamReader like @mhrimaz has shown.
Finally, to be sure the Strings from the test program are UTF-8 one should also include the flag for the encoding there.

I have created a pull request so you can view the resulting changes. The getJava() call is untouched and this works on my windows machine.

**Comment by alessiogambi** [comment]
I consider this closed. Reopen this, if you keep experiencing the same problem after (double) checking the new code.
