### ISSUE TITLE
FileTest should clearly tell where and how expected and actual output differ

### ISSUE THREAD

**Issue by alessiogambi** [se2p/programming-styles-ss-2020-public-tests#23]
File tests come with large input files, and it is not easy to debug when a problem actually is. So we need to improve the assertion mechanism to report not only that two string differ, but also how they do. One possibility might be [1].

Ideally, the test should notify also which requirement has been violated: it was the border? the message was wrong? the size of the banner? etc..

@mhrimaz and @Kombustor maybe you can take a look at this?

[1] https://stackoverflow.com/questions/12089967/find-difference-between-two-strings

**Comment by stocker4141** [comment]
I may have a solution in mind:
- Extend the BoardMatcher to show `<!> at index difference: stringDifference` after the lines with errors, where index is the index of the difference and stringDifference the actual difference computed by the StringUtils functions.
- Trim the outputs from the BoardMatcher to only show the first board with error. Otherwise, the mechanism above will go haywire if e.g. a move is missed and therefore all following boards are wrong.
- Use the BoardMatcher in the assertions from the FileTests.

That should be more verbose and carry over to the non FileTests. 
As for the javascript part of this issue, I have to admit that I am not familiar with mocha. Someone else might be more suited to do this half.

Does that sound like a good idea to you all?

**Comment by alessiogambi** [comment]
Sure, sounds good to me!

**Comment by alessiogambi** [comment]
Closed by #24
