### ISSUE TITLE
consider having input/output file for tests

### ISSUE THREAD

**Issue by mhrimaz** [se2p/programming-styles-ss-2020-public-tests#8]
I know, in general, using another source as input/output testing is not a good idea. But since we are testing against several platforms, it would be better to have separated files as input/output checking mechanisms. Otherwise, we need to rewrite all test cases, which would require much more effort.

**Comment by Kombustor** [comment]
Just to clarify - you mean we should create a common input/output file system to not rewrite all tests for javascript separately?

**Comment by alessiogambi** [comment]
I did that last year but found it quite cumbersome to manage and update. Additionally, you cannot easily extend the pipeline with additional analysis (e.g., coverage). I think that one easy way to go might be to reuse the Java tests for Javascripts? This would require extending the PSUtil class to run node in addition to java; eventually, we capture the output and can run the same assertions. However, this will impact the way you design (and hopefully debug!) your solution since testing and development take place on different platforms...
